Fix schema to allow descriptions-less apps
oakestra/oakestra pull request #232
Opened 2023-10-05 11:22 UTC by Malyuk-A

Resolves this issue: https://github.com/oakestra/dashboard/issues/37

2023-10-06 16:28 UTC, giobart requested changes
Regarding the instance of `data.get('application_desc')`, what do you think if we change them to `data.get('application_desc',"")`, this way, if no application_desc we return empty string, just in case? Just to avoid getting the orchestrator to fail because of a None around the code :D
Let me know.

2023-10-06 16:28 UTC, giobart commented on root_orchestrator/system-manager-python/sla/schema.py
Inside the test folder, there are a couple of tests concerning the SLA, do they still pass? Is it possible to create a new one including an SLA without a service description?

2023-10-12 07:17 UTC, Malyuk-A commented on root_orchestrator/system-manager-python/sla/schema.py
Nicely spotted!
I have added the default value to the data.get and added a new SLA test (and refactored the test a bit)

2023-10-12 09:43 UTC, giobart approved these changes

2023-10-12 09:44 UTC, giobart commented
Fixes #37

2023-10-12 09:44 UTC, merged