Ipv6 compatibility fix
oakestra/oakestra pull request #273
Opened 2024-02-07 16:25 UTC by smnzlnsk

- Added IPv6 support for resource abstractor
- Fixed IPv4 request incompatibility issues with request.remote_addr, which would cause it to be a 4to6 mapped IPv6 address
- Added overrides for IPv6 in **non**-1-DOC deployments
- Added override for local service manager builds (useful in automation scenarios)

2024-02-14 10:46 UTC, giobart requested changes

2024-02-14 10:46 UTC, giobart commented on cluster_orchestrator/override-ipv6-enabled.yml
what's the difference between enabled and addressed?

2024-02-14 10:46 UTC, giobart commented on cluster_orchestrator/override-local-service-manager.yml
Let's not push this without further instructions. It might just confuse people.

2024-02-14 10:46 UTC, giobart commented on root_orchestrator/override-local-service-manager.yml
Let's not push this without further instructions. It might just confuse people.

2024-02-14 10:46 UTC, giobart commented on root_orchestrator/system-manager-python/ext_requests/cluster_requests.py
> +            + sanitize(cluster.get("ip"), request=True)
👍👍

2024-02-14 11:11 UTC, smnzlnsk commented on cluster_orchestrator/override-ipv6-enabled.yml
Is documented in the README
Basically it changes the hostname inter-container addressing to static IPv6 addressing.
This way one can assure that a IPv4-to-IPv6 mapped IP address cannot be the case from inter-container traffic.
We can also remove it, as we addressed and fixed this.

2024-02-14 11:11 UTC, smnzlnsk commented on cluster_orchestrator/override-local-service-manager.yml
Added instructions to the README!

2024-02-14 12:34 UTC, giobart commented on cluster_orchestrator/override-ipv6-enabled.yml
Ok then if it's not necessary let's remove it

2024-02-14 17:21 UTC, smnzlnsk commented on cluster_orchestrator/override-ipv6-enabled.yml
I removed it, since it most likely is not needed.

2024-03-22 09:31 UTC, giobart approved these changes

2024-04-24 15:24 UTC, smnzlnsk commented
Merged with #280

2024-04-24 15:24 UTC, closed without merging