Github Workflow triggers image building during PR development (#260)
oakestra/oakestra pull request #314
Opened 2024-04-24 20:31 UTC by TheDarkPyotr

## Short
Test the building of a Docker image if `Dockerfile` or `requirements.txt` in any component across the project has been modified in the same PR

## Proposal
As widely explained in #260, this PR allows to avoid push the images to the registry that than results in failing building/containers. 
As discussed with @Malyuk-A, to avoid the execution overhead of triggering the image building at each commit, the proposal trigger the image building only when a change (*branch `develop`*) on the following files is detected:
 - `root_orchestrator/**/Dockerfile`
 - `root_orchestrator/**/requirements.txt`
 -  `cluster_orchestrator/**/Dockerfile`
 - `cluster_orchestrator/**/requirements.txt`
For each detected change, the Github Workflow spawn a job that build the image based on the supported platform.

## Impact
- `root_orchestrator/*`
- `cluster_orchestrator/*`

## Status
Tested locally by triggering different combinations of changes (*across different component and internally the same compoent, e.g. `cluster_orchestrator/cluster_scheduler` and/or `root_orchestrator/cloud-scheduler`*).
Limited the supported `platform` to `linux/amd64` (*~20 sec*) to limit the time overhead of building on all the supported platforms `linux/amd64, linux/armhf, linux/arm64`(*~2min*).

Following the suggestion in issue #260, refactoring the entire GitHub Actions workflow with a job spawn matrix could consolidate all workflow files into a single one, eliminating the need for multiple files like `cluster_manager_image.yml` , `cluster_scheduler_image.yml`, `root_resource_abstractor_image.yml`, ` root_scheduler_image.yml`, `root_system_manager_image.yml `.

The proposal can be optimized as the code still rely on commands concatenation to suitable dispatch the correct folders/parameters to each spawned job.

## Checklist
- [x] Discussed
- [x] Documented
- [x] Implemented: *can be surely optimized*
- [x] Tested: *a general usability test among the mantainers should clarify if it's a suitable solution or not*

Fixes #260

2024-05-15 09:03 UTC, giobart requested changes

2024-05-15 09:03 UTC, giobart commented on root_orchestrator/cloud-scheduler/Dockerfile
> +# Just a comment to check workflow triggering
maybe remove this and we're good to go

2024-07-26 12:47 UTC, giobart commented on cluster_orchestrator/config/dashboards/dashboard.json
Is this edit intentionally related to this PR?

2024-07-26 13:11 UTC, TheDarkPyotr commented on cluster_orchestrator/config/dashboards/dashboard.json
No, it is unintentional: I think it is due to having used different filters/moved some elements in the related dashboard. Let me remove it 👍

2024-07-29 09:02 UTC, giobart approved these changes

2024-07-29 09:03 UTC, merged