Use Maintained Compose Files
oakestra/oakestra pull request #367
Opened 2024-11-21 10:07 UTC by Mjaethers

The standalone build script now use the docker compose files that are used when manually building the Oakestra components. This means there is only one set of compose files that have to be maintained.
When building the warning `pull access denied for ...` is printed for multiple containers, however as far as I can tell everything still works.
Additionally instead of creating a directory in the home directory, it is placed in a new directory wherever the script is executed. I was confused by this when I used these scripts the first time myself.

2024-11-26 14:14 UTC, giobart commented on scripts/StartOakestraRoot.sh
> +cd root_orchestrator 2> /dev/null
the problem I have with this approach is that depending on where they execute the script the compose files are spread around the filesystem, and the stop command changes depending on that. When the startup and stop will be managed (@Malyuk-A will potentially execute these scripts as part of the CLI installation) a user does not even need to know where the compose files are, so it makes sense to keep them in a fixed pre-dermined folder right? Lmk what you think

2024-11-27 13:24 UTC, Mjaethers commented on scripts/StartOakestraRoot.sh
> +cd root_orchestrator 2> /dev/null
Okay, that makes sense. I'll be sure to clarify that this is placed in the home directory in the documentation then

2024-11-27 15:11 UTC, giobart requested changes

2024-11-27 15:11 UTC, giobart commented on scripts/StartOakestraCluster.sh
> +curl -sfL https://raw.githubusercontent.com/oakestra/oakestra/$OAKESTRA_BRANCH/cluster_orchestrator/docker-compose.yml > cluster-orchestrator.yml
this only works if people actually clone the Oakestra repo. 

`cluster_orchestrator/docker-compose.yml` manually builds the services.
while
`run-a-cluster/cluster-orchestrator.yml` should use the pre-built images.

With this script we don't want the user to clone Oak repo but this should run directly.

2024-11-27 15:11 UTC, giobart commented on scripts/StartOakestraRoot.sh
> +curl -sfL https://raw.githubusercontent.com/oakestra/oakestra/$OAKESTRA_BRANCH/root_orchestrator/docker-compose.yml > root-orchestrator.yml
Same problem as the cluster orchestrator script.

2024-11-27 15:12 UTC, giobart commented
> The standalone build scripts now use the docker compose files that are used when manually building the Oakestra components.

Mybe there is a misunderstanding.
This should not be the case in my opinion. We don't want to build Oakestra every time we need to deploy it but rather use the pre-built images we have. The run-a-cluster scripts serve this specific purpose, they use the pre-built images.

2024-11-28 21:49 UTC, Mjaethers commented
In terms of testing:
This is a bit of a chicken-and-egg problem, the script can't pull the compose override file as it was only created by this commit and has not been pushed to the main branch.
When testing with the new override files manually it works.

2024-12-04 12:42 UTC, giobart approved these changes

2024-12-04 12:42 UTC, giobart commented
LGTM! :)

2024-12-04 12:46 UTC, merged