Add support for WASM runtime
oakestra/oakestra pull request #373
Opened 2024-12-19 09:04 UTC by lucamarchiori

fixes #370

### Added WASM as a runtime type

- In `Node.go`, added `WASM_RUNTIME RuntimeType = "wasm"`.
- In `conf.go`, added a configuration option to enable or disable WASM runtime support. For example: `sudo NodeEngine config virtualization wasm on`

### Implemented Wasmtime as a WASM runtime

[Wasmtime](https://github.com/bytecodealliance/wasmtime) provides a [wasmtime-go](https://github.com/bytecodealliance/wasmtime-go) library to use precompiled binaries of Wasmtime directly from Go. However, the official library only supports Linux x86_64, macOS x86_64, and Windows x86_64. To support ARM as well, I added code to both `build.sh` and `install.sh` scripts to download the precompiled binaries of Wasmtime for both AMD64 and ARM. The library is installed in `/usr/local/lib/wasmtime-go` and linked dynamically with the appropriate CGO flags.

In case modifications to Wasmtime are needed (for example, to support custom functionalities), the C API of Wasmtime will need to be compiled from scratch and the wasmtime-go library that acts as a wrapper will need modifications as well.

`RuntimeDispatcher.go` has been updated to support the WASM runtime.  
`WasmManagement.go` has been created to support the deployment of WASM modules using Wasmtime with more or less the same logic that `UnikernelManagement` and `ContainersManagement` follow.

### Implemented pull of WASM modules

`WasmDownloader.go` has been created to support the pull of WASM modules from a cloud registry. Right now, only public repositories of Google Cloud Artifact Registry are supported.

### Example of WASM application deployment

```yaml
{
  "sla_version": "v2.0",
  "customerID": "6712177c9a65fd5275b1527e",
  "applications": [
    {
      "applicationID": "671220246855d2b9a5efeaae",
      "application_name": "WasmBenchmark",
      "application_namespace": "test",
      "microservices": [
        {
          "microserviceID": "",
          "microservice_name": "WasmBenchmark",
          "microservice_namespace": "ngnix",
          "virtualization": "wasm",
          "description": "Benchmark service run on Wasmtime without Docker",
          "memory": 250,
          "vcpus": 1,
          "vgpus": 0,
          "vtpus": 0,
          "bandwidth_in": 0,
          "bandwidth_out": 0,
          "storage": 0,
          "port": "80:90",
          "code": "https://artifactregistry.googleapis.com/download/v1/projects/wasmthesis/locations/europe-west3/repositories/wasmtestrepo/files/mypackage:1.0.0:GoBenchmarks.wasm:download?alt=media",
          "state": "",
          "added_files": [],
          "args": [],
          "environment": [],
          "constraints": [],
          "connectivity": []
        }
      ]
    }
  ]
}
```

Let me know if this proposal sounds good to you. I'll be more than happy to provide additional details and discuss with you improvements!

2025-02-05 10:36 UTC, giobart commented
Hello @lucamarchiori thanks for the PR!! :)  If you can fix this go.mod issues I can merge it to branch 370

2025-02-05 14:10 UTC, lucamarchiori commented
@giobart fixed conflicts

2025-02-25 14:42 UTC, giobart requested changes
can you remove nodeengined_amd64 and arm64 binaries from the PR?

2025-02-26 11:26 UTC, giobart commented on go_node_engine/build/NodeEngine_amd64
can we remove this binary as well?

2025-02-26 11:29 UTC, giobart commented on go_node_engine/build/README.md
Does this procedure work for pre-compiled node engines as well? Is it enough to simply build wasmtime in that case?

2025-02-26 11:32 UTC, giobart commented on go_node_engine/build/build.sh
Can we move the wasmtime build and installation as a separate script? eg. `go_node_engine/build/install_wasmtime.sh` This way we can allow wasmtime installation only if the user needs it.  so the install.sh and build.sh remain only for the node engine. Additionally, these install and build scripts will soon be replaced by a makefile.

2025-02-26 11:39 UTC, giobart commented on go_node_engine/cmd/root.go
> +	exec.Command("ldconfig", "/usr/local/lib/wasmtime-go").Run()
this should be executed only if wasm support is active, right?

2025-04-14 12:40 UTC, merged